
// generated by gocc; DO NOT EDIT.

package lexer



/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates] func(rune) int

var TransTab = TransitionTable{
	
		// S0
		func(r rune) int {
			switch {
			case r == 9 : // ['\t','\t']
				return 1
			case r == 10 : // ['\n','\n']
				return 1
			case r == 13 : // ['\r','\r']
				return 1
			case r == 32 : // [' ',' ']
				return 1
			case r == 33 : // ['!','!']
				return 2
			case r == 34 : // ['"','"']
				return 3
			case r == 39 : // [''',''']
				return 4
			case 48 <= r && r <= 57 : // ['0','9']
				return 5
			case r == 60 : // ['<','<']
				return 6
			case r == 61 : // ['=','=']
				return 7
			case r == 62 : // ['>','>']
				return 8
			case 65 <= r && r <= 90 : // ['A','Z']
				return 9
			case 97 <= r && r <= 98 : // ['a','b']
				return 9
			case r == 99 : // ['c','c']
				return 10
			case 100 <= r && r <= 101 : // ['d','e']
				return 9
			case r == 102 : // ['f','f']
				return 11
			case 103 <= r && r <= 104 : // ['g','h']
				return 9
			case r == 105 : // ['i','i']
				return 12
			case 106 <= r && r <= 108 : // ['j','l']
				return 9
			case r == 109 : // ['m','m']
				return 13
			case r == 110 : // ['n','n']
				return 14
			case 111 <= r && r <= 115 : // ['o','s']
				return 9
			case r == 116 : // ['t','t']
				return 15
			case 117 <= r && r <= 122 : // ['u','z']
				return 9
			
			
			
			}
			return NoState
			
		},
	
		// S1
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S2
		func(r rune) int {
			switch {
			case r == 61 : // ['=','=']
				return 16
			
			
			
			}
			return NoState
			
		},
	
		// S3
		func(r rune) int {
			switch {
			case r == 34 : // ['"','"']
				return 17
			
			
			default:
				return 3
			}
			
		},
	
		// S4
		func(r rune) int {
			switch {
			case r == 39 : // [''',''']
				return 17
			
			
			default:
				return 4
			}
			
		},
	
		// S5
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 18
			case 48 <= r && r <= 57 : // ['0','9']
				return 5
			
			
			
			}
			return NoState
			
		},
	
		// S6
		func(r rune) int {
			switch {
			case r == 61 : // ['=','=']
				return 19
			
			
			
			}
			return NoState
			
		},
	
		// S7
		func(r rune) int {
			switch {
			case r == 61 : // ['=','=']
				return 20
			
			
			
			}
			return NoState
			
		},
	
		// S8
		func(r rune) int {
			switch {
			case r == 61 : // ['=','=']
				return 21
			
			
			
			}
			return NoState
			
		},
	
		// S9
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 122 : // ['a','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S10
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 110 : // ['a','n']
				return 24
			case r == 111 : // ['o','o']
				return 25
			case 112 <= r && r <= 122 : // ['p','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S11
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case r == 97 : // ['a','a']
				return 26
			case 98 <= r && r <= 122 : // ['b','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S12
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 114 : // ['a','r']
				return 24
			case r == 115 : // ['s','s']
				return 27
			case 116 <= r && r <= 122 : // ['t','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S13
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case r == 97 : // ['a','a']
				return 28
			case 98 <= r && r <= 122 : // ['b','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S14
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 110 : // ['a','n']
				return 24
			case r == 111 : // ['o','o']
				return 29
			case 112 <= r && r <= 122 : // ['p','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S15
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 113 : // ['a','q']
				return 24
			case r == 114 : // ['r','r']
				return 30
			case 115 <= r && r <= 122 : // ['s','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S16
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S17
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S18
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 18
			case 48 <= r && r <= 57 : // ['0','9']
				return 31
			
			
			
			}
			return NoState
			
		},
	
		// S19
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S20
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S21
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S22
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 122 : // ['a','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S23
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 122 : // ['a','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S24
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 122 : // ['a','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S25
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 109 : // ['a','m']
				return 24
			case r == 110 : // ['n','n']
				return 32
			case 111 <= r && r <= 122 : // ['o','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S26
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 107 : // ['a','k']
				return 24
			case r == 108 : // ['l','l']
				return 33
			case 109 <= r && r <= 122 : // ['m','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S27
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 122 : // ['a','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S28
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 115 : // ['a','s']
				return 24
			case r == 116 : // ['t','t']
				return 34
			case 117 <= r && r <= 122 : // ['u','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S29
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 115 : // ['a','s']
				return 24
			case r == 116 : // ['t','t']
				return 35
			case 117 <= r && r <= 122 : // ['u','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S30
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 116 : // ['a','t']
				return 24
			case r == 117 : // ['u','u']
				return 36
			case 118 <= r && r <= 122 : // ['v','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S31
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 18
			case 48 <= r && r <= 57 : // ['0','9']
				return 31
			
			
			
			}
			return NoState
			
		},
	
		// S32
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 115 : // ['a','s']
				return 24
			case r == 116 : // ['t','t']
				return 37
			case 117 <= r && r <= 122 : // ['u','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S33
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 114 : // ['a','r']
				return 24
			case r == 115 : // ['s','s']
				return 38
			case 116 <= r && r <= 122 : // ['t','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S34
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 98 : // ['a','b']
				return 24
			case r == 99 : // ['c','c']
				return 39
			case 100 <= r && r <= 122 : // ['d','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S35
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 122 : // ['a','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S36
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 100 : // ['a','d']
				return 24
			case r == 101 : // ['e','e']
				return 40
			case 102 <= r && r <= 122 : // ['f','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S37
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case r == 97 : // ['a','a']
				return 41
			case 98 <= r && r <= 122 : // ['b','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S38
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 100 : // ['a','d']
				return 24
			case r == 101 : // ['e','e']
				return 42
			case 102 <= r && r <= 122 : // ['f','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S39
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 103 : // ['a','g']
				return 24
			case r == 104 : // ['h','h']
				return 43
			case 105 <= r && r <= 122 : // ['i','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S40
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 122 : // ['a','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S41
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 104 : // ['a','h']
				return 24
			case r == 105 : // ['i','i']
				return 44
			case 106 <= r && r <= 122 : // ['j','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S42
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 122 : // ['a','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S43
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 100 : // ['a','d']
				return 24
			case r == 101 : // ['e','e']
				return 45
			case 102 <= r && r <= 122 : // ['f','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S44
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 109 : // ['a','m']
				return 24
			case r == 110 : // ['n','n']
				return 46
			case 111 <= r && r <= 122 : // ['o','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S45
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 114 : // ['a','r']
				return 24
			case r == 115 : // ['s','s']
				return 47
			case 116 <= r && r <= 122 : // ['t','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S46
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 114 : // ['a','r']
				return 24
			case r == 115 : // ['s','s']
				return 48
			case 116 <= r && r <= 122 : // ['t','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S47
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 122 : // ['a','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
		// S48
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 22
			case 48 <= r && r <= 57 : // ['0','9']
				return 23
			case 65 <= r && r <= 90 : // ['A','Z']
				return 24
			case r == 95 : // ['_','_']
				return 22
			case 97 <= r && r <= 122 : // ['a','z']
				return 24
			
			
			
			}
			return NoState
			
		},
	
}
