
// generated by gocc; DO NOT EDIT.

package parser

type(
	actionTable [numStates]actionRow
	actionRow struct {
		canRecover bool
		actions [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(4),		/* variable */
			shift(5),		/* string_lit */
			shift(6),		/* int_lit */
			shift(7),		/* float_lit */
			shift(8),		/* true */
			shift(9),		/* false */
			
		},

	},
	actionRow{ // S1
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			accept(true),		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S2
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(2),		/* $, reduce: Expression */
			shift(10),		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S3
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(14),		/* $, reduce: Term */
			reduce(14),		/* or, reduce: Term */
			shift(11),		/* > */
			shift(12),		/* >= */
			shift(13),		/* < */
			shift(14),		/* <= */
			shift(15),		/* = */
			shift(16),		/* == */
			shift(17),		/* != */
			shift(18),		/* is */
			nil,		/* not */
			shift(19),		/* contains */
			shift(20),		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S4
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(15),		/* $, reduce: Factor */
			reduce(15),		/* or, reduce: Factor */
			reduce(15),		/* >, reduce: Factor */
			reduce(15),		/* >=, reduce: Factor */
			reduce(15),		/* <, reduce: Factor */
			reduce(15),		/* <=, reduce: Factor */
			reduce(15),		/* =, reduce: Factor */
			reduce(15),		/* ==, reduce: Factor */
			reduce(15),		/* !=, reduce: Factor */
			reduce(15),		/* is, reduce: Factor */
			nil,		/* not */
			reduce(15),		/* contains, reduce: Factor */
			reduce(15),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S5
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(16),		/* $, reduce: Factor */
			reduce(16),		/* or, reduce: Factor */
			reduce(16),		/* >, reduce: Factor */
			reduce(16),		/* >=, reduce: Factor */
			reduce(16),		/* <, reduce: Factor */
			reduce(16),		/* <=, reduce: Factor */
			reduce(16),		/* =, reduce: Factor */
			reduce(16),		/* ==, reduce: Factor */
			reduce(16),		/* !=, reduce: Factor */
			reduce(16),		/* is, reduce: Factor */
			nil,		/* not */
			reduce(16),		/* contains, reduce: Factor */
			reduce(16),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S6
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(17),		/* $, reduce: Factor */
			reduce(17),		/* or, reduce: Factor */
			reduce(17),		/* >, reduce: Factor */
			reduce(17),		/* >=, reduce: Factor */
			reduce(17),		/* <, reduce: Factor */
			reduce(17),		/* <=, reduce: Factor */
			reduce(17),		/* =, reduce: Factor */
			reduce(17),		/* ==, reduce: Factor */
			reduce(17),		/* !=, reduce: Factor */
			reduce(17),		/* is, reduce: Factor */
			nil,		/* not */
			reduce(17),		/* contains, reduce: Factor */
			reduce(17),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S7
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(18),		/* $, reduce: Factor */
			reduce(18),		/* or, reduce: Factor */
			reduce(18),		/* >, reduce: Factor */
			reduce(18),		/* >=, reduce: Factor */
			reduce(18),		/* <, reduce: Factor */
			reduce(18),		/* <=, reduce: Factor */
			reduce(18),		/* =, reduce: Factor */
			reduce(18),		/* ==, reduce: Factor */
			reduce(18),		/* !=, reduce: Factor */
			reduce(18),		/* is, reduce: Factor */
			nil,		/* not */
			reduce(18),		/* contains, reduce: Factor */
			reduce(18),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S8
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(19),		/* $, reduce: Factor */
			reduce(19),		/* or, reduce: Factor */
			reduce(19),		/* >, reduce: Factor */
			reduce(19),		/* >=, reduce: Factor */
			reduce(19),		/* <, reduce: Factor */
			reduce(19),		/* <=, reduce: Factor */
			reduce(19),		/* =, reduce: Factor */
			reduce(19),		/* ==, reduce: Factor */
			reduce(19),		/* !=, reduce: Factor */
			reduce(19),		/* is, reduce: Factor */
			nil,		/* not */
			reduce(19),		/* contains, reduce: Factor */
			reduce(19),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S9
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: Factor */
			reduce(20),		/* or, reduce: Factor */
			reduce(20),		/* >, reduce: Factor */
			reduce(20),		/* >=, reduce: Factor */
			reduce(20),		/* <, reduce: Factor */
			reduce(20),		/* <=, reduce: Factor */
			reduce(20),		/* =, reduce: Factor */
			reduce(20),		/* ==, reduce: Factor */
			reduce(20),		/* !=, reduce: Factor */
			reduce(20),		/* is, reduce: Factor */
			nil,		/* not */
			reduce(20),		/* contains, reduce: Factor */
			reduce(20),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S10
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(23),		/* variable */
			shift(24),		/* string_lit */
			shift(25),		/* int_lit */
			shift(26),		/* float_lit */
			shift(27),		/* true */
			shift(28),		/* false */
			
		},

	},
	actionRow{ // S11
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(30),		/* variable */
			shift(31),		/* string_lit */
			shift(32),		/* int_lit */
			shift(33),		/* float_lit */
			shift(34),		/* true */
			shift(35),		/* false */
			
		},

	},
	actionRow{ // S12
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(30),		/* variable */
			shift(31),		/* string_lit */
			shift(32),		/* int_lit */
			shift(33),		/* float_lit */
			shift(34),		/* true */
			shift(35),		/* false */
			
		},

	},
	actionRow{ // S13
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(30),		/* variable */
			shift(31),		/* string_lit */
			shift(32),		/* int_lit */
			shift(33),		/* float_lit */
			shift(34),		/* true */
			shift(35),		/* false */
			
		},

	},
	actionRow{ // S14
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(30),		/* variable */
			shift(31),		/* string_lit */
			shift(32),		/* int_lit */
			shift(33),		/* float_lit */
			shift(34),		/* true */
			shift(35),		/* false */
			
		},

	},
	actionRow{ // S15
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(30),		/* variable */
			shift(31),		/* string_lit */
			shift(32),		/* int_lit */
			shift(33),		/* float_lit */
			shift(34),		/* true */
			shift(35),		/* false */
			
		},

	},
	actionRow{ // S16
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(30),		/* variable */
			shift(31),		/* string_lit */
			shift(32),		/* int_lit */
			shift(33),		/* float_lit */
			shift(34),		/* true */
			shift(35),		/* false */
			
		},

	},
	actionRow{ // S17
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(30),		/* variable */
			shift(31),		/* string_lit */
			shift(32),		/* int_lit */
			shift(33),		/* float_lit */
			shift(34),		/* true */
			shift(35),		/* false */
			
		},

	},
	actionRow{ // S18
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			shift(43),		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(30),		/* variable */
			shift(31),		/* string_lit */
			shift(32),		/* int_lit */
			shift(33),		/* float_lit */
			shift(34),		/* true */
			shift(35),		/* false */
			
		},

	},
	actionRow{ // S19
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(30),		/* variable */
			shift(31),		/* string_lit */
			shift(32),		/* int_lit */
			shift(33),		/* float_lit */
			shift(34),		/* true */
			shift(35),		/* false */
			
		},

	},
	actionRow{ // S20
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(30),		/* variable */
			shift(31),		/* string_lit */
			shift(32),		/* int_lit */
			shift(33),		/* float_lit */
			shift(34),		/* true */
			shift(35),		/* false */
			
		},

	},
	actionRow{ // S21
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(1),		/* $, reduce: Expression */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S22
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(14),		/* $, reduce: Term */
			nil,		/* or */
			shift(46),		/* > */
			shift(47),		/* >= */
			shift(48),		/* < */
			shift(49),		/* <= */
			shift(50),		/* = */
			shift(51),		/* == */
			shift(52),		/* != */
			shift(53),		/* is */
			nil,		/* not */
			shift(54),		/* contains */
			shift(55),		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S23
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(15),		/* $, reduce: Factor */
			nil,		/* or */
			reduce(15),		/* >, reduce: Factor */
			reduce(15),		/* >=, reduce: Factor */
			reduce(15),		/* <, reduce: Factor */
			reduce(15),		/* <=, reduce: Factor */
			reduce(15),		/* =, reduce: Factor */
			reduce(15),		/* ==, reduce: Factor */
			reduce(15),		/* !=, reduce: Factor */
			reduce(15),		/* is, reduce: Factor */
			nil,		/* not */
			reduce(15),		/* contains, reduce: Factor */
			reduce(15),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S24
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(16),		/* $, reduce: Factor */
			nil,		/* or */
			reduce(16),		/* >, reduce: Factor */
			reduce(16),		/* >=, reduce: Factor */
			reduce(16),		/* <, reduce: Factor */
			reduce(16),		/* <=, reduce: Factor */
			reduce(16),		/* =, reduce: Factor */
			reduce(16),		/* ==, reduce: Factor */
			reduce(16),		/* !=, reduce: Factor */
			reduce(16),		/* is, reduce: Factor */
			nil,		/* not */
			reduce(16),		/* contains, reduce: Factor */
			reduce(16),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S25
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(17),		/* $, reduce: Factor */
			nil,		/* or */
			reduce(17),		/* >, reduce: Factor */
			reduce(17),		/* >=, reduce: Factor */
			reduce(17),		/* <, reduce: Factor */
			reduce(17),		/* <=, reduce: Factor */
			reduce(17),		/* =, reduce: Factor */
			reduce(17),		/* ==, reduce: Factor */
			reduce(17),		/* !=, reduce: Factor */
			reduce(17),		/* is, reduce: Factor */
			nil,		/* not */
			reduce(17),		/* contains, reduce: Factor */
			reduce(17),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S26
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(18),		/* $, reduce: Factor */
			nil,		/* or */
			reduce(18),		/* >, reduce: Factor */
			reduce(18),		/* >=, reduce: Factor */
			reduce(18),		/* <, reduce: Factor */
			reduce(18),		/* <=, reduce: Factor */
			reduce(18),		/* =, reduce: Factor */
			reduce(18),		/* ==, reduce: Factor */
			reduce(18),		/* !=, reduce: Factor */
			reduce(18),		/* is, reduce: Factor */
			nil,		/* not */
			reduce(18),		/* contains, reduce: Factor */
			reduce(18),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S27
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(19),		/* $, reduce: Factor */
			nil,		/* or */
			reduce(19),		/* >, reduce: Factor */
			reduce(19),		/* >=, reduce: Factor */
			reduce(19),		/* <, reduce: Factor */
			reduce(19),		/* <=, reduce: Factor */
			reduce(19),		/* =, reduce: Factor */
			reduce(19),		/* ==, reduce: Factor */
			reduce(19),		/* !=, reduce: Factor */
			reduce(19),		/* is, reduce: Factor */
			nil,		/* not */
			reduce(19),		/* contains, reduce: Factor */
			reduce(19),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S28
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: Factor */
			nil,		/* or */
			reduce(20),		/* >, reduce: Factor */
			reduce(20),		/* >=, reduce: Factor */
			reduce(20),		/* <, reduce: Factor */
			reduce(20),		/* <=, reduce: Factor */
			reduce(20),		/* =, reduce: Factor */
			reduce(20),		/* ==, reduce: Factor */
			reduce(20),		/* !=, reduce: Factor */
			reduce(20),		/* is, reduce: Factor */
			nil,		/* not */
			reduce(20),		/* contains, reduce: Factor */
			reduce(20),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S29
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(3),		/* $, reduce: Term */
			reduce(3),		/* or, reduce: Term */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S30
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(15),		/* $, reduce: Factor */
			reduce(15),		/* or, reduce: Factor */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S31
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(16),		/* $, reduce: Factor */
			reduce(16),		/* or, reduce: Factor */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S32
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(17),		/* $, reduce: Factor */
			reduce(17),		/* or, reduce: Factor */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S33
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(18),		/* $, reduce: Factor */
			reduce(18),		/* or, reduce: Factor */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S34
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(19),		/* $, reduce: Factor */
			reduce(19),		/* or, reduce: Factor */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S35
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: Factor */
			reduce(20),		/* or, reduce: Factor */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S36
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(4),		/* $, reduce: Term */
			reduce(4),		/* or, reduce: Term */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S37
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(5),		/* $, reduce: Term */
			reduce(5),		/* or, reduce: Term */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S38
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(6),		/* $, reduce: Term */
			reduce(6),		/* or, reduce: Term */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S39
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(7),		/* $, reduce: Term */
			reduce(7),		/* or, reduce: Term */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S40
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(8),		/* $, reduce: Term */
			reduce(8),		/* or, reduce: Term */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S41
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(9),		/* $, reduce: Term */
			reduce(9),		/* or, reduce: Term */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S42
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(10),		/* $, reduce: Term */
			reduce(10),		/* or, reduce: Term */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S43
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(30),		/* variable */
			shift(31),		/* string_lit */
			shift(32),		/* int_lit */
			shift(33),		/* float_lit */
			shift(34),		/* true */
			shift(35),		/* false */
			
		},

	},
	actionRow{ // S44
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(12),		/* $, reduce: Term */
			reduce(12),		/* or, reduce: Term */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S45
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(13),		/* $, reduce: Term */
			reduce(13),		/* or, reduce: Term */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S46
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(58),		/* variable */
			shift(59),		/* string_lit */
			shift(60),		/* int_lit */
			shift(61),		/* float_lit */
			shift(62),		/* true */
			shift(63),		/* false */
			
		},

	},
	actionRow{ // S47
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(58),		/* variable */
			shift(59),		/* string_lit */
			shift(60),		/* int_lit */
			shift(61),		/* float_lit */
			shift(62),		/* true */
			shift(63),		/* false */
			
		},

	},
	actionRow{ // S48
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(58),		/* variable */
			shift(59),		/* string_lit */
			shift(60),		/* int_lit */
			shift(61),		/* float_lit */
			shift(62),		/* true */
			shift(63),		/* false */
			
		},

	},
	actionRow{ // S49
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(58),		/* variable */
			shift(59),		/* string_lit */
			shift(60),		/* int_lit */
			shift(61),		/* float_lit */
			shift(62),		/* true */
			shift(63),		/* false */
			
		},

	},
	actionRow{ // S50
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(58),		/* variable */
			shift(59),		/* string_lit */
			shift(60),		/* int_lit */
			shift(61),		/* float_lit */
			shift(62),		/* true */
			shift(63),		/* false */
			
		},

	},
	actionRow{ // S51
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(58),		/* variable */
			shift(59),		/* string_lit */
			shift(60),		/* int_lit */
			shift(61),		/* float_lit */
			shift(62),		/* true */
			shift(63),		/* false */
			
		},

	},
	actionRow{ // S52
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(58),		/* variable */
			shift(59),		/* string_lit */
			shift(60),		/* int_lit */
			shift(61),		/* float_lit */
			shift(62),		/* true */
			shift(63),		/* false */
			
		},

	},
	actionRow{ // S53
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			shift(71),		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(58),		/* variable */
			shift(59),		/* string_lit */
			shift(60),		/* int_lit */
			shift(61),		/* float_lit */
			shift(62),		/* true */
			shift(63),		/* false */
			
		},

	},
	actionRow{ // S54
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(58),		/* variable */
			shift(59),		/* string_lit */
			shift(60),		/* int_lit */
			shift(61),		/* float_lit */
			shift(62),		/* true */
			shift(63),		/* false */
			
		},

	},
	actionRow{ // S55
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(58),		/* variable */
			shift(59),		/* string_lit */
			shift(60),		/* int_lit */
			shift(61),		/* float_lit */
			shift(62),		/* true */
			shift(63),		/* false */
			
		},

	},
	actionRow{ // S56
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(11),		/* $, reduce: Term */
			reduce(11),		/* or, reduce: Term */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S57
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(3),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S58
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(15),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S59
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(16),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S60
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(17),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S61
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(18),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S62
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(19),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S63
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S64
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(4),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S65
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(5),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S66
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(6),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S67
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(7),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S68
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(8),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S69
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(9),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S70
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(10),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S71
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			shift(58),		/* variable */
			shift(59),		/* string_lit */
			shift(60),		/* int_lit */
			shift(61),		/* float_lit */
			shift(62),		/* true */
			shift(63),		/* false */
			
		},

	},
	actionRow{ // S72
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(12),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S73
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(13),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	actionRow{ // S74
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(11),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* not */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			nil,		/* true */
			nil,		/* false */
			
		},

	},
	
}

