
// generated by gocc; DO NOT EDIT.

package parser

type(
	actionTable [numStates]actionRow
	actionRow struct {
		canRecover bool
		actions [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			shift(3),		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(5),		/* true */
			shift(6),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(7),		/* variable */
			shift(8),		/* string_lit */
			shift(9),		/* int_lit */
			shift(10),		/* float_lit */
			
		},

	},
	actionRow{ // S1
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			accept(true),		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S2
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(4),		/* $, reduce: Expression */
			shift(11),		/* or */
			shift(12),		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S3
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(15),		/* true */
			shift(16),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(17),		/* variable */
			shift(18),		/* string_lit */
			shift(19),		/* int_lit */
			shift(20),		/* float_lit */
			
		},

	},
	actionRow{ // S4
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(19),		/* $, reduce: Term */
			reduce(19),		/* or, reduce: Term */
			reduce(19),		/* and, reduce: Term */
			nil,		/* not */
			shift(21),		/* > */
			shift(22),		/* >= */
			shift(23),		/* < */
			shift(24),		/* <= */
			shift(25),		/* = */
			nil,		/* true */
			nil,		/* false */
			shift(26),		/* == */
			shift(27),		/* != */
			shift(28),		/* is */
			shift(29),		/* contains */
			shift(30),		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S5
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(24),		/* $, reduce: Factor */
			reduce(24),		/* or, reduce: Factor */
			reduce(24),		/* and, reduce: Factor */
			nil,		/* not */
			reduce(24),		/* >, reduce: Factor */
			reduce(24),		/* >=, reduce: Factor */
			reduce(24),		/* <, reduce: Factor */
			reduce(24),		/* <=, reduce: Factor */
			reduce(24),		/* =, reduce: Factor */
			nil,		/* true */
			nil,		/* false */
			reduce(24),		/* ==, reduce: Factor */
			reduce(24),		/* !=, reduce: Factor */
			reduce(24),		/* is, reduce: Factor */
			reduce(24),		/* contains, reduce: Factor */
			reduce(24),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S6
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			nil,		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			nil,		/* true */
			nil,		/* false */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S7
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: Factor */
			reduce(20),		/* or, reduce: Factor */
			reduce(20),		/* and, reduce: Factor */
			nil,		/* not */
			reduce(20),		/* >, reduce: Factor */
			reduce(20),		/* >=, reduce: Factor */
			reduce(20),		/* <, reduce: Factor */
			reduce(20),		/* <=, reduce: Factor */
			reduce(20),		/* =, reduce: Factor */
			nil,		/* true */
			nil,		/* false */
			reduce(20),		/* ==, reduce: Factor */
			reduce(20),		/* !=, reduce: Factor */
			reduce(20),		/* is, reduce: Factor */
			reduce(20),		/* contains, reduce: Factor */
			reduce(20),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S8
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(21),		/* $, reduce: Factor */
			reduce(21),		/* or, reduce: Factor */
			reduce(21),		/* and, reduce: Factor */
			nil,		/* not */
			reduce(21),		/* >, reduce: Factor */
			reduce(21),		/* >=, reduce: Factor */
			reduce(21),		/* <, reduce: Factor */
			reduce(21),		/* <=, reduce: Factor */
			reduce(21),		/* =, reduce: Factor */
			nil,		/* true */
			nil,		/* false */
			reduce(21),		/* ==, reduce: Factor */
			reduce(21),		/* !=, reduce: Factor */
			reduce(21),		/* is, reduce: Factor */
			reduce(21),		/* contains, reduce: Factor */
			reduce(21),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S9
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(22),		/* $, reduce: Factor */
			reduce(22),		/* or, reduce: Factor */
			reduce(22),		/* and, reduce: Factor */
			nil,		/* not */
			reduce(22),		/* >, reduce: Factor */
			reduce(22),		/* >=, reduce: Factor */
			reduce(22),		/* <, reduce: Factor */
			reduce(22),		/* <=, reduce: Factor */
			reduce(22),		/* =, reduce: Factor */
			nil,		/* true */
			nil,		/* false */
			reduce(22),		/* ==, reduce: Factor */
			reduce(22),		/* !=, reduce: Factor */
			reduce(22),		/* is, reduce: Factor */
			reduce(22),		/* contains, reduce: Factor */
			reduce(22),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S10
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(23),		/* $, reduce: Factor */
			reduce(23),		/* or, reduce: Factor */
			reduce(23),		/* and, reduce: Factor */
			nil,		/* not */
			reduce(23),		/* >, reduce: Factor */
			reduce(23),		/* >=, reduce: Factor */
			reduce(23),		/* <, reduce: Factor */
			reduce(23),		/* <=, reduce: Factor */
			reduce(23),		/* =, reduce: Factor */
			nil,		/* true */
			nil,		/* false */
			reduce(23),		/* ==, reduce: Factor */
			reduce(23),		/* !=, reduce: Factor */
			reduce(23),		/* is, reduce: Factor */
			reduce(23),		/* contains, reduce: Factor */
			reduce(23),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S11
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(15),		/* true */
			shift(16),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(17),		/* variable */
			shift(18),		/* string_lit */
			shift(19),		/* int_lit */
			shift(20),		/* float_lit */
			
		},

	},
	actionRow{ // S12
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(15),		/* true */
			shift(16),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(17),		/* variable */
			shift(18),		/* string_lit */
			shift(19),		/* int_lit */
			shift(20),		/* float_lit */
			
		},

	},
	actionRow{ // S13
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(3),		/* $, reduce: Expression */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S14
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(19),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			shift(33),		/* > */
			shift(34),		/* >= */
			shift(35),		/* < */
			shift(36),		/* <= */
			shift(37),		/* = */
			nil,		/* true */
			nil,		/* false */
			shift(38),		/* == */
			shift(39),		/* != */
			shift(40),		/* is */
			shift(41),		/* contains */
			shift(42),		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S15
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(24),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			reduce(24),		/* >, reduce: Factor */
			reduce(24),		/* >=, reduce: Factor */
			reduce(24),		/* <, reduce: Factor */
			reduce(24),		/* <=, reduce: Factor */
			reduce(24),		/* =, reduce: Factor */
			nil,		/* true */
			nil,		/* false */
			reduce(24),		/* ==, reduce: Factor */
			reduce(24),		/* !=, reduce: Factor */
			reduce(24),		/* is, reduce: Factor */
			reduce(24),		/* contains, reduce: Factor */
			reduce(24),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S16
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			nil,		/* true */
			nil,		/* false */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S17
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			reduce(20),		/* >, reduce: Factor */
			reduce(20),		/* >=, reduce: Factor */
			reduce(20),		/* <, reduce: Factor */
			reduce(20),		/* <=, reduce: Factor */
			reduce(20),		/* =, reduce: Factor */
			nil,		/* true */
			nil,		/* false */
			reduce(20),		/* ==, reduce: Factor */
			reduce(20),		/* !=, reduce: Factor */
			reduce(20),		/* is, reduce: Factor */
			reduce(20),		/* contains, reduce: Factor */
			reduce(20),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S18
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(21),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			reduce(21),		/* >, reduce: Factor */
			reduce(21),		/* >=, reduce: Factor */
			reduce(21),		/* <, reduce: Factor */
			reduce(21),		/* <=, reduce: Factor */
			reduce(21),		/* =, reduce: Factor */
			nil,		/* true */
			nil,		/* false */
			reduce(21),		/* ==, reduce: Factor */
			reduce(21),		/* !=, reduce: Factor */
			reduce(21),		/* is, reduce: Factor */
			reduce(21),		/* contains, reduce: Factor */
			reduce(21),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S19
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(22),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			reduce(22),		/* >, reduce: Factor */
			reduce(22),		/* >=, reduce: Factor */
			reduce(22),		/* <, reduce: Factor */
			reduce(22),		/* <=, reduce: Factor */
			reduce(22),		/* =, reduce: Factor */
			nil,		/* true */
			nil,		/* false */
			reduce(22),		/* ==, reduce: Factor */
			reduce(22),		/* !=, reduce: Factor */
			reduce(22),		/* is, reduce: Factor */
			reduce(22),		/* contains, reduce: Factor */
			reduce(22),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S20
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(23),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			reduce(23),		/* >, reduce: Factor */
			reduce(23),		/* >=, reduce: Factor */
			reduce(23),		/* <, reduce: Factor */
			reduce(23),		/* <=, reduce: Factor */
			reduce(23),		/* =, reduce: Factor */
			nil,		/* true */
			nil,		/* false */
			reduce(23),		/* ==, reduce: Factor */
			reduce(23),		/* !=, reduce: Factor */
			reduce(23),		/* is, reduce: Factor */
			reduce(23),		/* contains, reduce: Factor */
			reduce(23),		/* matches, reduce: Factor */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S21
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(44),		/* true */
			shift(45),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(46),		/* variable */
			shift(47),		/* string_lit */
			shift(48),		/* int_lit */
			shift(49),		/* float_lit */
			
		},

	},
	actionRow{ // S22
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(44),		/* true */
			shift(45),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(46),		/* variable */
			shift(47),		/* string_lit */
			shift(48),		/* int_lit */
			shift(49),		/* float_lit */
			
		},

	},
	actionRow{ // S23
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(44),		/* true */
			shift(45),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(46),		/* variable */
			shift(47),		/* string_lit */
			shift(48),		/* int_lit */
			shift(49),		/* float_lit */
			
		},

	},
	actionRow{ // S24
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(44),		/* true */
			shift(45),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(46),		/* variable */
			shift(47),		/* string_lit */
			shift(48),		/* int_lit */
			shift(49),		/* float_lit */
			
		},

	},
	actionRow{ // S25
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(54),		/* true */
			shift(55),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(46),		/* variable */
			shift(47),		/* string_lit */
			shift(48),		/* int_lit */
			shift(49),		/* float_lit */
			
		},

	},
	actionRow{ // S26
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(44),		/* true */
			shift(45),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(46),		/* variable */
			shift(47),		/* string_lit */
			shift(48),		/* int_lit */
			shift(49),		/* float_lit */
			
		},

	},
	actionRow{ // S27
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(44),		/* true */
			shift(45),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(46),		/* variable */
			shift(47),		/* string_lit */
			shift(48),		/* int_lit */
			shift(49),		/* float_lit */
			
		},

	},
	actionRow{ // S28
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			shift(58),		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(44),		/* true */
			shift(45),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(46),		/* variable */
			shift(47),		/* string_lit */
			shift(48),		/* int_lit */
			shift(49),		/* float_lit */
			
		},

	},
	actionRow{ // S29
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(44),		/* true */
			shift(45),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(46),		/* variable */
			shift(47),		/* string_lit */
			shift(48),		/* int_lit */
			shift(49),		/* float_lit */
			
		},

	},
	actionRow{ // S30
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(44),		/* true */
			shift(45),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(46),		/* variable */
			shift(47),		/* string_lit */
			shift(48),		/* int_lit */
			shift(49),		/* float_lit */
			
		},

	},
	actionRow{ // S31
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(1),		/* $, reduce: Expression */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S32
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(2),		/* $, reduce: Expression */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S33
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(63),		/* true */
			shift(64),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(65),		/* variable */
			shift(66),		/* string_lit */
			shift(67),		/* int_lit */
			shift(68),		/* float_lit */
			
		},

	},
	actionRow{ // S34
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(63),		/* true */
			shift(64),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(65),		/* variable */
			shift(66),		/* string_lit */
			shift(67),		/* int_lit */
			shift(68),		/* float_lit */
			
		},

	},
	actionRow{ // S35
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(63),		/* true */
			shift(64),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(65),		/* variable */
			shift(66),		/* string_lit */
			shift(67),		/* int_lit */
			shift(68),		/* float_lit */
			
		},

	},
	actionRow{ // S36
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(63),		/* true */
			shift(64),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(65),		/* variable */
			shift(66),		/* string_lit */
			shift(67),		/* int_lit */
			shift(68),		/* float_lit */
			
		},

	},
	actionRow{ // S37
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(73),		/* true */
			shift(74),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(65),		/* variable */
			shift(66),		/* string_lit */
			shift(67),		/* int_lit */
			shift(68),		/* float_lit */
			
		},

	},
	actionRow{ // S38
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(63),		/* true */
			shift(64),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(65),		/* variable */
			shift(66),		/* string_lit */
			shift(67),		/* int_lit */
			shift(68),		/* float_lit */
			
		},

	},
	actionRow{ // S39
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(63),		/* true */
			shift(64),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(65),		/* variable */
			shift(66),		/* string_lit */
			shift(67),		/* int_lit */
			shift(68),		/* float_lit */
			
		},

	},
	actionRow{ // S40
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			shift(77),		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(63),		/* true */
			shift(64),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(65),		/* variable */
			shift(66),		/* string_lit */
			shift(67),		/* int_lit */
			shift(68),		/* float_lit */
			
		},

	},
	actionRow{ // S41
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(63),		/* true */
			shift(64),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(65),		/* variable */
			shift(66),		/* string_lit */
			shift(67),		/* int_lit */
			shift(68),		/* float_lit */
			
		},

	},
	actionRow{ // S42
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(63),		/* true */
			shift(64),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(65),		/* variable */
			shift(66),		/* string_lit */
			shift(67),		/* int_lit */
			shift(68),		/* float_lit */
			
		},

	},
	actionRow{ // S43
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(5),		/* $, reduce: Term */
			reduce(5),		/* or, reduce: Term */
			reduce(5),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S44
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(24),		/* $, reduce: Factor */
			reduce(24),		/* or, reduce: Factor */
			reduce(24),		/* and, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S45
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S46
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: Factor */
			reduce(20),		/* or, reduce: Factor */
			reduce(20),		/* and, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S47
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(21),		/* $, reduce: Factor */
			reduce(21),		/* or, reduce: Factor */
			reduce(21),		/* and, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S48
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(22),		/* $, reduce: Factor */
			reduce(22),		/* or, reduce: Factor */
			reduce(22),		/* and, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S49
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(23),		/* $, reduce: Factor */
			reduce(23),		/* or, reduce: Factor */
			reduce(23),		/* and, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S50
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(6),		/* $, reduce: Term */
			reduce(6),		/* or, reduce: Term */
			reduce(6),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S51
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(7),		/* $, reduce: Term */
			reduce(7),		/* or, reduce: Term */
			reduce(7),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S52
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(8),		/* $, reduce: Term */
			reduce(8),		/* or, reduce: Term */
			reduce(8),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S53
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(11),		/* $, reduce: Term */
			reduce(11),		/* or, reduce: Term */
			reduce(11),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S54
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(9),		/* $, reduce: Term */
			reduce(9),		/* or, reduce: Term */
			reduce(9),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S55
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(10),		/* $, reduce: Term */
			reduce(10),		/* or, reduce: Term */
			reduce(10),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S56
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(13),		/* $, reduce: Term */
			reduce(13),		/* or, reduce: Term */
			reduce(13),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S57
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(14),		/* $, reduce: Term */
			reduce(14),		/* or, reduce: Term */
			reduce(14),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S58
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(44),		/* true */
			shift(45),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(46),		/* variable */
			shift(47),		/* string_lit */
			shift(48),		/* int_lit */
			shift(49),		/* float_lit */
			
		},

	},
	actionRow{ // S59
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(15),		/* $, reduce: Term */
			reduce(15),		/* or, reduce: Term */
			reduce(15),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S60
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(17),		/* $, reduce: Term */
			reduce(17),		/* or, reduce: Term */
			reduce(17),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S61
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(18),		/* $, reduce: Term */
			reduce(18),		/* or, reduce: Term */
			reduce(18),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S62
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(5),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S63
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(24),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S64
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S65
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S66
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(21),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S67
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(22),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S68
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(23),		/* $, reduce: Factor */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S69
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(6),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S70
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(7),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S71
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(8),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S72
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(11),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S73
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(9),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S74
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(10),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S75
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(13),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S76
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(14),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S77
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			shift(63),		/* true */
			shift(64),		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(65),		/* variable */
			shift(66),		/* string_lit */
			shift(67),		/* int_lit */
			shift(68),		/* float_lit */
			
		},

	},
	actionRow{ // S78
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(15),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S79
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(17),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S80
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(18),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S81
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(16),		/* $, reduce: Term */
			reduce(16),		/* or, reduce: Term */
			reduce(16),		/* and, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	actionRow{ // S82
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(16),		/* $, reduce: Term */
			nil,		/* or */
			nil,		/* and */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* true */
			nil,		/* false */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* variable */
			nil,		/* string_lit */
			nil,		/* int_lit */
			nil,		/* float_lit */
			
		},

	},
	
}

