
// generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 4
type(
	gotoTable [numStates]gotoRow
	gotoRow	[numNTSymbols] int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		
		-1, // S'
		1, // Expression
		2, // Term
		3, // Factor
		

	},
	gotoRow{ // S1
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S2
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S3
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S4
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S5
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S6
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S7
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S8
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S9
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S10
		
		-1, // S'
		-1, // Expression
		21, // Term
		22, // Factor
		

	},
	gotoRow{ // S11
		
		-1, // S'
		-1, // Expression
		-1, // Term
		29, // Factor
		

	},
	gotoRow{ // S12
		
		-1, // S'
		-1, // Expression
		-1, // Term
		36, // Factor
		

	},
	gotoRow{ // S13
		
		-1, // S'
		-1, // Expression
		-1, // Term
		37, // Factor
		

	},
	gotoRow{ // S14
		
		-1, // S'
		-1, // Expression
		-1, // Term
		38, // Factor
		

	},
	gotoRow{ // S15
		
		-1, // S'
		-1, // Expression
		-1, // Term
		39, // Factor
		

	},
	gotoRow{ // S16
		
		-1, // S'
		-1, // Expression
		-1, // Term
		40, // Factor
		

	},
	gotoRow{ // S17
		
		-1, // S'
		-1, // Expression
		-1, // Term
		41, // Factor
		

	},
	gotoRow{ // S18
		
		-1, // S'
		-1, // Expression
		-1, // Term
		42, // Factor
		

	},
	gotoRow{ // S19
		
		-1, // S'
		-1, // Expression
		-1, // Term
		44, // Factor
		

	},
	gotoRow{ // S20
		
		-1, // S'
		-1, // Expression
		-1, // Term
		45, // Factor
		

	},
	gotoRow{ // S21
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S22
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S23
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S24
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S25
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S26
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S27
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S28
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S29
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S30
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S31
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S32
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S33
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S34
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S35
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S36
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S37
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S38
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S39
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S40
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S41
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S42
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S43
		
		-1, // S'
		-1, // Expression
		-1, // Term
		56, // Factor
		

	},
	gotoRow{ // S44
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S45
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S46
		
		-1, // S'
		-1, // Expression
		-1, // Term
		57, // Factor
		

	},
	gotoRow{ // S47
		
		-1, // S'
		-1, // Expression
		-1, // Term
		64, // Factor
		

	},
	gotoRow{ // S48
		
		-1, // S'
		-1, // Expression
		-1, // Term
		65, // Factor
		

	},
	gotoRow{ // S49
		
		-1, // S'
		-1, // Expression
		-1, // Term
		66, // Factor
		

	},
	gotoRow{ // S50
		
		-1, // S'
		-1, // Expression
		-1, // Term
		67, // Factor
		

	},
	gotoRow{ // S51
		
		-1, // S'
		-1, // Expression
		-1, // Term
		68, // Factor
		

	},
	gotoRow{ // S52
		
		-1, // S'
		-1, // Expression
		-1, // Term
		69, // Factor
		

	},
	gotoRow{ // S53
		
		-1, // S'
		-1, // Expression
		-1, // Term
		70, // Factor
		

	},
	gotoRow{ // S54
		
		-1, // S'
		-1, // Expression
		-1, // Term
		72, // Factor
		

	},
	gotoRow{ // S55
		
		-1, // S'
		-1, // Expression
		-1, // Term
		73, // Factor
		

	},
	gotoRow{ // S56
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S57
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S58
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S59
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S60
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S61
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S62
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S63
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S64
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S65
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S66
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S67
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S68
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S69
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S70
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S71
		
		-1, // S'
		-1, // Expression
		-1, // Term
		74, // Factor
		

	},
	gotoRow{ // S72
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S73
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S74
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	
}
